version: '3.6'

services:

  #1. Vue Frontend
  dentte_frontend:
    build:
      context: .
      dockerfile: ./docker/vue3/Dockerfile
      ############################
      # WHEN ADDING OR REMOVING FROM HERE, PLEASE UPDATE /docker/vue3/Dockerfile
      #args:
      #  REACT_APP_NAME: "DENTTE"
      ############################
    image: registry.gitlab.com/dentte/dentte-frontend/frontend:latest
    container_name: dentte_frontend
    restart: always
    tty: true
    env_file:
      - ./.env
      - ./src/.env
    environment:
      ############################
      - CHOKIDAR_USEPOLLING=true
      ############################
    working_dir: /app
    ports:
      - "3000:3000" # vue3
      - "9090:8080" # fake json server
      - "4000:4000" # dont remember
      - "6001:6001" # vite hot reload (hmr)
    volumes:
      - ./src/:/app
      - node_modules:/app/node_modules
    networks:
      - network_dentte_proxy

  # Nginx Service
  nginx_dentte_frontend:
    image: nginx:alpine
    container_name: nginx_dentte_frontend
    restart: always
    tty: true
    ports:
      - "8080:80"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      # Nginx Main Conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      # Nginx Virtual Hosts
      - ./docker/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      # Certificates
      - ./docker/nginx/certificates/app.dentte.com.br/:/var/www/app.dentte.com.br/certificates/certificates/
      # Web Root
      #- ./src/:/var/www/app.dentte.com.br/public
    depends_on:
      - dentte_frontend
    networks:
      network_dentte_proxy:
          aliases:
            - local.app.dentte.com.br
            - app.dentte.com.br

networks:
  network_dentte_proxy:
    driver: bridge
    name: network_dentte_proxy

volumes:
  node_modules:
    name: dentte_frontend_node_modules